version: "3.9"

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  web:
    build:
      context: blockchain
      dockerfile: Dockerfile
    command: bash -c "while !</dev/tcp/db/5432; do sleep 1; done; uvicorn main:app --host 0.0.0.0 --port 8000 --log-level debug --reload"
    env_file:
      - .env
    volumes:
      - "./blockchain:/app"
    ports:
      - "8000:8000"