"""add data sign

Revision ID: b5186c5b0d35
Revises: be5bdfc4fed3
Create Date: 2022-09-26 19:47:51.329165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5186c5b0d35'
down_revision = 'be5bdfc4fed3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('block', sa.Column('data_sign', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('block', 'data_sign')
    # ### end Alembic commands ###
